<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectAll</name>
   <tag></tag>
   <elementGuidId>79514825-eac0-44d6-8b3d-be7bd5d84fab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#enableDisableAllAdapters > div.control.custom.checkbox > label.control--checkbox > div.control__indicator</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='enableDisableAllAdapters']/div/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>15aaff9d-ec55-4839-bd29-ca1e609b70a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control__indicator</value>
      <webElementGuid>50f41a67-981c-4a39-998c-57c71cc31eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myGrid&quot;)/div[@class=&quot;ag-root-wrapper ag-layout-normal ag-ltr ag-keyboard-focus&quot;]/div[@class=&quot;ag-root-wrapper-body ag-layout-normal&quot;]/div[@class=&quot;ag-root ag-unselectable ag-layout-normal&quot;]/div[@class=&quot;ag-header ag-pivot-off&quot;]/div[@class=&quot;ag-header-viewport&quot;]/div[@class=&quot;ag-header-container&quot;]/div[@class=&quot;ag-header-row ag-header-row-column&quot;]/div[@class=&quot;ag-header-cell ag-column-hover&quot;]/div[@id=&quot;enableDisableAllAdapters&quot;]/div[@class=&quot;control custom checkbox&quot;]/label[@class=&quot;control--checkbox&quot;]/div[@class=&quot;control__indicator&quot;]</value>
      <webElementGuid>11d7e1e7-e060-40f0-82de-a7651a2779a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='enableDisableAllAdapters']/div/label/div</value>
      <webElementGuid>3167e0fb-402a-45dc-950d-836b7de19347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/label/div</value>
      <webElementGuid>9486737b-0034-4fd2-9898-2b6f5bdbd089</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
