<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Communication Channel</name>
   <tag></tag>
   <elementGuidId>a2c77eae-fed8-447a-9d2d-e52435d1b46b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ag-header-cell.ag-header-cell-sortable.grid-header-cell-style.ag-column-hover > div.ag-cell-label-container.ag-header-cell-sorted-none > div.ag-header-cell-label > span.ag-header-cell-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myGrid']/div/div/div/div/div[2]/div/div/div[4]/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ddc519a9-0068-4b6e-81d8-e9a53044956b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eText</value>
      <webElementGuid>d5d4d469-0295-41f6-8814-918e4ac1eb54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-header-cell-text</value>
      <webElementGuid>03c3a870-b4d9-4fd5-ae10-d5cca9a7a47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>columnheader</value>
      <webElementGuid>fb782cf1-c39b-4917-b6ad-4bed6803243c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>1e3c2b3d-fdbc-4637-8505-ed65996f21e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>fe0490b7-5616-4a1b-af75-e301de88fcec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Communication Channel</value>
      <webElementGuid>62b778d7-91ba-41cf-9ad0-35a70a20618f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myGrid&quot;)/div[@class=&quot;ag-root-wrapper ag-layout-normal ag-ltr ag-keyboard-focus&quot;]/div[@class=&quot;ag-root-wrapper-body ag-layout-normal&quot;]/div[@class=&quot;ag-root ag-unselectable ag-layout-normal&quot;]/div[@class=&quot;ag-header ag-pivot-off&quot;]/div[@class=&quot;ag-header-viewport&quot;]/div[@class=&quot;ag-header-container&quot;]/div[@class=&quot;ag-header-row ag-header-row-column&quot;]/div[@class=&quot;ag-header-cell ag-header-cell-sortable grid-header-cell-style ag-column-hover&quot;]/div[@class=&quot;ag-cell-label-container ag-header-cell-sorted-none&quot;]/div[@class=&quot;ag-header-cell-label&quot;]/span[@class=&quot;ag-header-cell-text&quot;]</value>
      <webElementGuid>39d0a25c-296f-498e-a4a2-688b6b180b9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myGrid']/div/div/div/div/div[2]/div/div/div[4]/div[2]/div/span</value>
      <webElementGuid>bc9cf0b0-b25d-43c3-941b-84b37d8de198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group'])[1]/following::span[10]</value>
      <webElementGuid>9e031e1f-c956-48a7-8adf-072e16026bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adapter Name'])[2]/following::span[20]</value>
      <webElementGuid>5ec15201-e24e-4f41-a8ce-066c3cd11844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adapter Enable/Disable'])[1]/preceding::span[10]</value>
      <webElementGuid>9059e8c0-0b1c-4711-90dc-f6290106b1e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/preceding::span[13]</value>
      <webElementGuid>d6287f25-14dd-4725-9571-c482c20ac005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Communication Channel']/parent::*</value>
      <webElementGuid>3e7dc475-46c8-48f6-957d-eff522b70fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/span</value>
      <webElementGuid>57687f64-542d-44e0-8cc2-18f25fcb2b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Communication Channel' or . = 'Communication Channel')]</value>
      <webElementGuid>2e05d5ec-7218-416b-a065-44055edb0e6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
