<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Group</name>
   <tag></tag>
   <elementGuidId>33811903-70b9-4f28-98ab-6043ccb8e971</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ag-cell-label-container.ag-header-cell-sorted-none > div.ag-header-cell-label > span.ag-header-cell-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myGrid']/div/div/div/div/div[2]/div/div/div[3]/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fa3e38d2-e678-405c-8585-d62bf14618cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eText</value>
      <webElementGuid>9de12ea5-cc5b-4777-ad65-3b578b948794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-header-cell-text</value>
      <webElementGuid>4e69b3e5-7aa1-4842-af26-14e87eab98d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>columnheader</value>
      <webElementGuid>b2c105ec-7316-4591-aa6a-93be35eb58b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>8186c13c-2f19-4ba4-9d15-3cb7aea6a831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d5541271-ede4-49f6-b446-010f603ef2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Group</value>
      <webElementGuid>ef031cc1-0e6a-4c62-a205-32ebd13b0949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myGrid&quot;)/div[@class=&quot;ag-root-wrapper ag-layout-normal ag-ltr ag-keyboard-focus&quot;]/div[@class=&quot;ag-root-wrapper-body ag-layout-normal&quot;]/div[@class=&quot;ag-root ag-unselectable ag-layout-normal&quot;]/div[@class=&quot;ag-header ag-pivot-off&quot;]/div[@class=&quot;ag-header-viewport&quot;]/div[@class=&quot;ag-header-container&quot;]/div[@class=&quot;ag-header-row ag-header-row-column&quot;]/div[@class=&quot;ag-header-cell ag-header-cell-sortable grid-header-cell-style ag-column-hover&quot;]/div[@class=&quot;ag-cell-label-container ag-header-cell-sorted-none&quot;]/div[@class=&quot;ag-header-cell-label&quot;]/span[@class=&quot;ag-header-cell-text&quot;]</value>
      <webElementGuid>22964700-383f-4eb4-ab8f-c809a3693308</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myGrid']/div/div/div/div/div[2]/div/div/div[3]/div[2]/div/span</value>
      <webElementGuid>63ac757c-fff7-4e2c-a056-bdd1e9c5d303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adapter Name'])[2]/following::span[10]</value>
      <webElementGuid>7e935d95-5bef-47f4-83f1-ba85c6f1c5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of records per page:'])[1]/following::span[14]</value>
      <webElementGuid>65dc5a59-1aea-4f94-9a80-4f8d73cec36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Communication Channel'])[1]/preceding::span[10]</value>
      <webElementGuid>b83ad28b-bab7-443b-8424-0be31b51e14f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adapter Enable/Disable'])[1]/preceding::span[20]</value>
      <webElementGuid>343df2c5-84b9-4550-be59-c7ab393b9ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Group']/parent::*</value>
      <webElementGuid>4e517ba8-d081-4d3d-8939-094c82337be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/span</value>
      <webElementGuid>5622a8ff-f881-4600-9e72-40c3d2762953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Group' or . = 'Group')]</value>
      <webElementGuid>2d41e73e-8a36-4e9b-877a-03e882a65a14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
