<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Adapter Name</name>
   <tag></tag>
   <elementGuidId>9d8816cd-a903-4b83-8ab7-fb5bda0df8ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ag-header-cell-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myGrid']/div/div/div/div/div[2]/div/div/div[2]/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2965a40e-890c-450e-9aa1-e35f2e5f852c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eText</value>
      <webElementGuid>2505ab68-bd78-4d47-be5f-1a7d1ae35f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-header-cell-text</value>
      <webElementGuid>c60a0372-051b-4721-9015-533878938d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>columnheader</value>
      <webElementGuid>a7479828-c82d-4dea-9fa1-e834ee69cd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>fb44a2c2-2ab3-47df-b0e4-9cc84929e4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>df5e2733-4c9c-442f-9973-ee70988f7724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adapter Name</value>
      <webElementGuid>ead54fe6-e768-44e5-9c1a-ba02ef0ab2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myGrid&quot;)/div[@class=&quot;ag-root-wrapper ag-layout-normal ag-ltr ag-keyboard-focus&quot;]/div[@class=&quot;ag-root-wrapper-body ag-layout-normal&quot;]/div[@class=&quot;ag-root ag-unselectable ag-layout-normal&quot;]/div[@class=&quot;ag-header ag-pivot-off&quot;]/div[@class=&quot;ag-header-viewport&quot;]/div[@class=&quot;ag-header-container&quot;]/div[@class=&quot;ag-header-row ag-header-row-column&quot;]/div[@class=&quot;ag-header-cell ag-header-cell-sortable grid-header-cell-style ag-column-hover&quot;]/div[@class=&quot;ag-cell-label-container ag-header-cell-sorted-asc&quot;]/div[@class=&quot;ag-header-cell-label&quot;]/span[@class=&quot;ag-header-cell-text&quot;]</value>
      <webElementGuid>a415eb06-d24b-4d0f-bbe7-2b40f6f154e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myGrid']/div/div/div/div/div[2]/div/div/div[2]/div[2]/div/span</value>
      <webElementGuid>ff807360-ef8b-4ef6-b6d3-3bd1b0918f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of records per page:'])[1]/following::span[4]</value>
      <webElementGuid>a3871918-c297-4b51-9cdf-df573164af54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disable'])[1]/following::span[5]</value>
      <webElementGuid>6c46c478-7e86-4d6e-9bb3-31b0e27a9f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group'])[1]/preceding::span[10]</value>
      <webElementGuid>be3a8a9f-208d-4ec5-b95e-45d0811059db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Communication Channel'])[1]/preceding::span[20]</value>
      <webElementGuid>35019b66-6cad-4b54-9526-90f3ede2430a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>1af7d489-bc10-4c89-8f94-bf0a9540eb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Adapter Name' or . = 'Adapter Name')]</value>
      <webElementGuid>8cb1a293-22b9-4e57-88cc-6080fd70fad8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
