<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Adapter EnableDisable</name>
   <tag></tag>
   <elementGuidId>6a07c8b7-74aa-4f8b-aaeb-338e0a3a0c76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ag-header-cell.grid-header-cell-style.ag-column-hover > div.ag-cell-label-container > div.ag-header-cell-label > span.ag-header-cell-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myGrid']/div/div/div/div/div[2]/div/div/div[5]/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>feb4f4fc-c0d4-4acd-825c-eea3d1a164b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eText</value>
      <webElementGuid>53362edf-f3c8-45c0-b9e3-404b7f04ed8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-header-cell-text</value>
      <webElementGuid>9f5948a6-5d5e-49dd-9af1-96d1faa19ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>columnheader</value>
      <webElementGuid>13558b48-dbf0-4dc6-860f-95924325d9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>5de88ef1-bee8-4b67-8b30-15bb9bc9fb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>83a15d5c-5ea8-4b4d-b5e9-db03b1c5140d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adapter Enable/Disable</value>
      <webElementGuid>0fbaf36d-ca0c-482f-9f66-b1b524cad3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myGrid&quot;)/div[@class=&quot;ag-root-wrapper ag-layout-normal ag-ltr ag-keyboard-focus&quot;]/div[@class=&quot;ag-root-wrapper-body ag-layout-normal&quot;]/div[@class=&quot;ag-root ag-unselectable ag-layout-normal&quot;]/div[@class=&quot;ag-header ag-pivot-off&quot;]/div[@class=&quot;ag-header-viewport&quot;]/div[@class=&quot;ag-header-container&quot;]/div[@class=&quot;ag-header-row ag-header-row-column&quot;]/div[@class=&quot;ag-header-cell grid-header-cell-style ag-column-hover&quot;]/div[@class=&quot;ag-cell-label-container&quot;]/div[@class=&quot;ag-header-cell-label&quot;]/span[@class=&quot;ag-header-cell-text&quot;]</value>
      <webElementGuid>bf96728e-02e3-4332-8137-4799e97dfa58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myGrid']/div/div/div/div/div[2]/div/div/div[5]/div[2]/div/span</value>
      <webElementGuid>23887768-82b0-48be-b789-0f662273e8b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Communication Channel'])[1]/following::span[10]</value>
      <webElementGuid>e3abd84c-583e-46e9-bd6f-155eb28e5575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group'])[1]/following::span[20]</value>
      <webElementGuid>ba3a5701-a29c-452f-8dfa-4c8a00988834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/preceding::span[3]</value>
      <webElementGuid>ac8d331e-8bec-4a26-b669-564522a0aeea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adam Adapter 1'])[2]/preceding::span[7]</value>
      <webElementGuid>daf65616-92b4-4a98-9654-7ba1143bacda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Adapter Enable/Disable']/parent::*</value>
      <webElementGuid>a9d673ef-6280-4741-959c-93ee3d51ef14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/span</value>
      <webElementGuid>f9973f12-587b-4306-8b44-296baa678ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Adapter Enable/Disable' or . = 'Adapter Enable/Disable')]</value>
      <webElementGuid>0370de15-fd37-43d5-85c5-15334d660f53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
