<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cross_icon</name>
   <tag></tag>
   <elementGuidId>8e351709-7c45-4480-b264-dc5de0aef841</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#close_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='close_7314fb17-bf21-4c1a-8ffd-bbd832677e5c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9a2aaf14-3753-49d3-bfd1-d0db1699ccde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2c05d334-bdcd-47f0-992a-c5504e0fd6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      <webElementGuid>564217b7-292e-4955-be0d-a9b5a131eb5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-remove-circle</value>
      <webElementGuid>af77873c-e2e4-448d-a2bc-2972f3981f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>closeConfigurationSlider(id)</value>
      <webElementGuid>3d39b829-b6ff-43d0-9b2e-435f26e3a3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>close_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      <webElementGuid>548fb779-ff2b-4d27-a971-3c84ade90103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close_7314fb17-bf21-4c1a-8ffd-bbd832677e5c&quot;)</value>
      <webElementGuid>81a94745-bb22-432b-a20b-a2ad9876524b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='close_7314fb17-bf21-4c1a-8ffd-bbd832677e5c']</value>
      <webElementGuid>eb31177f-51bb-4782-b301-17efaa902e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headingOne']/h4/a[2]</value>
      <webElementGuid>3bcf08e7-496b-4de7-a635-84a61daad79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
      <webElementGuid>ca351765-d2b5-41cd-9406-17e6242a4e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/a[2]</value>
      <webElementGuid>b67aa760-0aa8-4d0b-b30d-886afaa1ada2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'close_7314fb17-bf21-4c1a-8ffd-bbd832677e5c' and @name = 'close_7314fb17-bf21-4c1a-8ffd-bbd832677e5c']</value>
      <webElementGuid>8c207a48-27a3-4070-bec3-e64daf125519</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
