<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Group Name</name>
   <tag></tag>
   <elementGuidId>14a2756c-2b94-424e-8ed3-543b4f5c54bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eVoSHEGroupName_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'GroupName_')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b2d0c80-0ac1-431a-b194-8beb0d77137c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7968f38a-e059-467b-9b98-07c0aeaaf6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control tooltipster uniqueAdapterName tooltipstered</value>
      <webElementGuid>a45141b1-e4ef-4580-827f-bde6a4b17a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eVoSHEGroupName_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      <webElementGuid>519a5715-3cfe-4425-a1bc-0dc1e2cb7b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>eVoSHEGroupName_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      <webElementGuid>8a8f03f6-dafe-432e-8747-880e6414ba24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eVoSHEGroupName_7314fb17-bf21-4c1a-8ffd-bbd832677e5c&quot;)</value>
      <webElementGuid>d1c6f531-e5fc-407d-b9f5-471af6708937</webElementGuid>
   </webElementProperties>
</WebElementEntity>
