<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Port</name>
   <tag></tag>
   <elementGuidId>8c659905-59d7-4e77-86a6-6194a0f29002</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eVoSHEModbusPort_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'ModbusPort_')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71efc335-337b-40a4-9419-d22e5f594d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ffa11699-2906-4669-91b3-f5329faec023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control tooltipster tooltipstered</value>
      <webElementGuid>ef4601f2-255b-4ac9-b875-bc0da02030d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eVoSHEModbusPort_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      <webElementGuid>802813d2-1d88-4dc2-b22c-7877158de99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>eVoSHEModbusPort_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      <webElementGuid>f8df6107-1b18-4900-9602-d84ebba1fc5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eVoSHEModbusPort_7314fb17-bf21-4c1a-8ffd-bbd832677e5c&quot;)</value>
      <webElementGuid>703111e1-3791-491f-9f41-d387bcbfbd77</webElementGuid>
   </webElementProperties>
</WebElementEntity>
