<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IP</name>
   <tag></tag>
   <elementGuidId>a5b5ef05-afb6-41b0-833b-020f1c113144</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eVoSHEModbusIP_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'IP_')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcb78eaf-72ea-47ac-a226-4d7bf70adf13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0ca4b4e-40ab-4531-8682-60dedae4f6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control tooltipster tooltipstered</value>
      <webElementGuid>0b0fef1e-79bf-4b37-8aea-9d5278968462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eVoSHEModbusIP_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      <webElementGuid>81472548-d32a-4fce-9065-38b1f9570609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>eVoSHEModbusIP_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      <webElementGuid>face33f5-f305-4c0b-b0ee-dad97fcf5c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eVoSHEModbusIP_7314fb17-bf21-4c1a-8ffd-bbd832677e5c&quot;)</value>
      <webElementGuid>6d5296d5-3b79-4419-8355-67175e53d2d7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
