<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_IP</name>
   <tag></tag>
   <elementGuidId>c31fcf50-663a-45e9-a655-25337a9c5248</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eVoSHEIpField_7314fb17-bf21-4c1a-8ffd-bbd832677e5c > div.col-lg-4 > div.holder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@class='custom-label'][contains(text(),'IP')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a2f2e0d4-7a78-4068-95a8-c0c1b64365fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>holder</value>
      <webElementGuid>07fbd855-2670-4ec8-a772-4dcd0f6d1fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            IP
                                        </value>
      <webElementGuid>57588a4b-bb8f-42e9-b492-6d945821c116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eVoSHEIpField_7314fb17-bf21-4c1a-8ffd-bbd832677e5c&quot;)/div[@class=&quot;col-lg-4&quot;]/div[@class=&quot;holder&quot;]</value>
      <webElementGuid>f699fce9-dbcd-4703-935f-32fc2cd53d4c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
