<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DEMO MODE</name>
   <tag></tag>
   <elementGuidId>31381425-24e1-40d3-8c06-3bdaca69b4cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.demo-indicator</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4795d033-b57a-41ee-8d2a-c373529fdc21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>demo-indicator</value>
      <webElementGuid>2961eb3a-99f0-4562-be9b-8c70c167c7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DEMO MODE</value>
      <webElementGuid>49d472e8-6b5a-4206-a45d-b31e625a1b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;demo-indicator&quot;]</value>
      <webElementGuid>311c6bce-171c-4cde-9f00-663f91bcf5ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div</value>
      <webElementGuid>2d059e7b-216e-43ee-9eeb-35e09080f91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::div[1]</value>
      <webElementGuid>9b19d527-5b70-48ca-90b5-033ab02af9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License Options'])[1]/following::div[1]</value>
      <webElementGuid>5dd10252-d73e-427d-a19d-6aa7fde663cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Link'])[1]/preceding::div[1]</value>
      <webElementGuid>a7a17a4c-2534-4857-808b-a9fadc0da906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div</value>
      <webElementGuid>db91fc01-839b-44ce-a836-f57a4b3ee023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DEMO MODE' or . = 'DEMO MODE')]</value>
      <webElementGuid>992cf8f1-949f-43a3-b344-b7c6508de8f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
