<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconNotificationBell</name>
   <tag></tag>
   <elementGuidId>ae89368b-0402-4888-a210-af3e2a66edf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.icon-bell-o.notification-bell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bell']/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>11da27e1-8a6a-4f13-8500-175127f49dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Notifications</value>
      <webElementGuid>bc57d45b-3542-4abc-8f98-81fa8e3d789c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-bell-o notification-bell</value>
      <webElementGuid>0da09c48-6645-4d11-af53-137093c4fc88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bell&quot;)/a[@class=&quot;icon-bell-o notification-bell&quot;]</value>
      <webElementGuid>4c88f17f-28a1-4711-b9c8-394b22c7dd96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bell']/a[3]</value>
      <webElementGuid>3a7efbe4-6631-4ec2-89f6-fa4bf1bc0adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Description'])[1]/following::a[1]</value>
      <webElementGuid>d2b61118-16f1-402b-ab00-8d9f1465e0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Title'])[1]/following::a[2]</value>
      <webElementGuid>579311b4-53b9-44e4-a5d3-a575895ab127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear all'])[1]/preceding::a[1]</value>
      <webElementGuid>19db186a-0c23-4552-ba6a-8f70567f8699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>e454e1e1-5f47-40c9-8ba6-8a22d3b393a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Notifications']</value>
      <webElementGuid>d5f12846-774e-4989-861e-6ca4c9a4986f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
