<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconExportDashboardJson</name>
   <tag></tag>
   <elementGuidId>5f49fcf0-ed0e-4bf3-b967-5d90297aaed7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.icon-Export.icoImportExport</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bell']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ce8a6760-f991-4c6b-8c4c-f293405bc191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>bd06a0c3-61d8-4cf6-ad51-68cb15247fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Export dashboard</value>
      <webElementGuid>741b77e6-2cb6-4b33-8380-8f4fd03e5d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-Export icoImportExport</value>
      <webElementGuid>e3fa275f-9e3a-450d-bcb6-036072344ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://172.18.199.82//edgeui/api/dashboard/export</value>
      <webElementGuid>bf683eed-7a36-4e9d-8108-812f771840df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bell&quot;)/a[@class=&quot;icon-Export icoImportExport&quot;]</value>
      <webElementGuid>ffb2a1b2-a33b-4205-a5f7-d2630dc4d688</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bell']/a</value>
      <webElementGuid>90d2b4bf-387c-4d47-894a-437867a477ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://172.18.199.82//edgeui/api/dashboard/export']</value>
      <webElementGuid>bec57f82-5d51-4dab-99db-6384a6dc35de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>b8434988-98ad-4567-ab1e-ee750e1d4c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Export dashboard' and @href = 'http://172.18.199.82//edgeui/api/dashboard/export']</value>
      <webElementGuid>71ea6ec3-877f-4f7f-acbf-f2683e53b969</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
