<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DEMO MODE</name>
   <tag></tag>
   <elementGuidId>ced7c186-9b64-4155-8655-2de79b853d85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.demo-indicator-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>370fc70d-8357-4822-a8fa-bdd692322615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>demo-indicator-text</value>
      <webElementGuid>6ed04823-5ba9-4c70-baac-e60365201457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DEMO MODE</value>
      <webElementGuid>e7977f06-b61c-4797-8ccd-9a88bc3addf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;demo-indicator&quot;]/span[@class=&quot;demo-indicator-text&quot;]</value>
      <webElementGuid>23d6fe36-0fa6-4ea5-abe5-fc2928824436</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/span</value>
      <webElementGuid>30844ec3-703d-4934-a86f-65c0f10ade9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::span[1]</value>
      <webElementGuid>e025cf6d-9dd0-4e1c-8ee6-a85900689c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License Options'])[1]/following::span[4]</value>
      <webElementGuid>68f33a9c-249c-4184-8cec-4780504e63c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Link'])[1]/preceding::span[1]</value>
      <webElementGuid>1bd0ac6c-5460-4567-a0de-64785f795125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Title'])[1]/preceding::span[1]</value>
      <webElementGuid>7b6018e9-b4e7-4f0e-92d3-c093b54e473b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DEMO MODE']/parent::*</value>
      <webElementGuid>3fe60a85-f80f-4cf2-bd60-c9042a674b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>987e4fa4-9c13-44ea-8c7e-6acd588102f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'DEMO MODE' or . = 'DEMO MODE')]</value>
      <webElementGuid>e59a56b1-8494-4ce1-ae6f-c2dd6c07eb46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
