<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>advanceConfigs_dropdown</name>
   <tag></tag>
   <elementGuidId>d6774638-4936-4a8a-b2cc-1fa4d6d8809d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#advanceSettingsPanel_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@id,'advanceSettingsPanel_')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71f46159-c395-4b08-ad3c-e50f16720ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advanceSettingsPanel_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      <webElementGuid>ec47ac8f-cb77-4bc0-8296-ab0927f59b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>013f79de-9687-4954-9cd9-9c67492eb684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordion</value>
      <webElementGuid>8a35b21c-daaa-4f55-91c6-d72189fabd81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#collapseTwo_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      <webElementGuid>ff5d7085-424f-4ccc-ae04-f13df6e45750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-circle-up</value>
      <webElementGuid>fc1f1e07-dab6-48c8-b701-6bdf6a027b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AdvanceSettingCollapse(this.id)</value>
      <webElementGuid>0290fead-76e4-457d-b8cf-d89933e2bc9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>advanceSettingsPanel_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      <webElementGuid>53948ce2-e309-4172-9317-fdc06e00e33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8e7856db-b675-44f8-99cd-92f34bf71791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advanceSettingsPanel_7314fb17-bf21-4c1a-8ffd-bbd832677e5c&quot;)</value>
      <webElementGuid>626882cb-007a-4d3c-b8f0-5504652031f7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
