<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Commands_Icon</name>
   <tag></tag>
   <elementGuidId>e581b607-74c7-4dba-89f0-86b4fd504d5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@id,'cmdsListBtn')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cmdsListBtn_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d4252759-5347-4e74-9c18-ca6d58a1c3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c027d4ed-f82b-4b4f-a72f-552bde7425c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cmdsListBtn_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      <webElementGuid>7f658ffc-6eaf-4094-b5d4-e913c39406bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>76911b2e-b5cf-406a-8cfe-b4424363d8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return openCmdsListView(this.id)</value>
      <webElementGuid>8af94038-5623-4e43-ba1e-026090e5aeec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cmdsListBtn_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      <webElementGuid>e3e0aec5-dbfc-45cd-8a21-bc2a74da5969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmdsListBtn_7314fb17-bf21-4c1a-8ffd-bbd832677e5c&quot;)</value>
      <webElementGuid>e5572396-5488-4244-8a3e-f937532f304f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
