<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AE Bus Address</name>
   <tag></tag>
   <elementGuidId>caf92d8a-ba75-474b-9467-db11674282c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eVoSHEAddress_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='eVoSHEAddress_7314fb17-bf21-4c1a-8ffd-bbd832677e5c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8576d1e-0137-4328-a90d-3127671696ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4c5ac987-6817-4cbf-a497-9c5e8f0ef369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>273b4ee2-976b-4083-adf6-c7bb3b74c9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>f3388df4-8c15-4e2e-9765-c54a257155fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control tooltipster tooltipstered</value>
      <webElementGuid>4e81e8ee-4f06-437f-9464-29cbd5b228de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eVoSHEAddress_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      <webElementGuid>e71e1c89-5f6e-455e-bdd1-71ccd5e0cbca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>eVoSHEAddress_7314fb17-bf21-4c1a-8ffd-bbd832677e5c</value>
      <webElementGuid>0c1e01e8-2b7c-4746-921d-903b497379d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eVoSHEAddress_7314fb17-bf21-4c1a-8ffd-bbd832677e5c&quot;)</value>
      <webElementGuid>27446b35-f6d4-42c9-93ea-0564836e0785</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='eVoSHEAddress_7314fb17-bf21-4c1a-8ffd-bbd832677e5c']</value>
      <webElementGuid>82c0d715-eb11-4506-8b4b-5d0e928dad56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eVoSHEAddressSection_7314fb17-bf21-4c1a-8ffd-bbd832677e5c']/div[2]/div/div/input</value>
      <webElementGuid>1ce5ba25-59b0-425c-8712-76133f65d4d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/input</value>
      <webElementGuid>a89ee61b-a8e5-421e-bdec-2d0f5b7b25ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'eVoSHEAddress_7314fb17-bf21-4c1a-8ffd-bbd832677e5c' and @name = 'eVoSHEAddress_7314fb17-bf21-4c1a-8ffd-bbd832677e5c']</value>
      <webElementGuid>e414b746-7185-4723-ad14-89189357abc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
