<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Commands</name>
   <tag></tag>
   <elementGuidId>412b1234-fcb1-4421-91a9-9f2d60cf6b0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@class='custom-label'][contains(text(),'Commands')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eVoSHECmdsConfig_7314fb17-bf21-4c1a-8ffd-bbd832677e5c > div.col-lg-4 > div.holder > label.custom-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d1c3e425-666e-44b6-96a2-b2b2e9e16583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-label</value>
      <webElementGuid>574b62ea-e5f6-42b0-a593-b9d1330c0fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Commands</value>
      <webElementGuid>4b11a779-8324-4b19-a542-7b7eb56cf5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eVoSHECmdsConfig_7314fb17-bf21-4c1a-8ffd-bbd832677e5c&quot;)/div[@class=&quot;col-lg-4&quot;]/div[@class=&quot;holder&quot;]/label[@class=&quot;custom-label&quot;]</value>
      <webElementGuid>0ebc8fc3-f8b2-4c4b-ab6d-90ba97ea93b2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
