<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_AE Bus Address</name>
   <tag></tag>
   <elementGuidId>91772ef0-eb01-4492-b031-c5f97692f327</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eVoSHEAddressSection_7314fb17-bf21-4c1a-8ffd-bbd832677e5c > div.col-lg-4 > div.holder > label.custom-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='eVoSHEAddressSection_7314fb17-bf21-4c1a-8ffd-bbd832677e5c']/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>585fbe36-5060-45ea-8e56-87ec5465702c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-label</value>
      <webElementGuid>03807981-3963-44aa-b6d7-7b151bfe5852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AE Bus Address</value>
      <webElementGuid>96c04d5f-9e2b-4755-ae65-5073ea4ebf82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eVoSHEAddressSection_7314fb17-bf21-4c1a-8ffd-bbd832677e5c&quot;)/div[@class=&quot;col-lg-4&quot;]/div[@class=&quot;holder&quot;]/label[@class=&quot;custom-label&quot;]</value>
      <webElementGuid>710e1a6e-fc26-4442-a751-fa45d32122e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eVoSHEAddressSection_7314fb17-bf21-4c1a-8ffd-bbd832677e5c']/div/div/label</value>
      <webElementGuid>2247cfda-ed31-45de-a4a2-866ce90f944f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One'])[2]/following::label[1]</value>
      <webElementGuid>dd5a8a3d-2f27-41b1-816a-3fb67a659230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stop Bit'])[1]/following::label[1]</value>
      <webElementGuid>10e2b240-c764-4bcd-8b35-cf3f3a1830da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='InputAdapter'])[1]/preceding::label[1]</value>
      <webElementGuid>3f34ecae-62c3-4cb5-a8e3-121756889f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disable Slow Speed Data'])[1]/preceding::label[1]</value>
      <webElementGuid>03c0467d-1d51-4f37-867b-bbf89563b03c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AE Bus Address']/parent::*</value>
      <webElementGuid>7546fdee-52dd-4be2-8c46-9110d0d83a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[6]/div/div/label</value>
      <webElementGuid>9791ee84-f55e-4dec-a559-f942c37583af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'AE Bus Address' or . = 'AE Bus Address')]</value>
      <webElementGuid>e92e6796-1d39-4b88-8076-e7f76223926f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
