<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radioButton_Ethernet</name>
   <tag></tag>
   <elementGuidId>a40f69f2-7787-4726-b62d-38fe6eb61e76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@class='mode-label'][contains(text(),'Ethernet')]//preceding-sibling::div[@class='control__indicator']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
