<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radioButton_Serial</name>
   <tag></tag>
   <elementGuidId>e6975c22-d833-4e43-a3c0-1113b2ff56e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@class='mode-label'][contains(text(),'Serial')]//preceding-sibling::div[@class='control__indicator']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
