<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit_action</name>
   <tag></tag>
   <elementGuidId>cd62f0cb-0c6f-4e37-8932-4f7fc49f3209</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit_a1fe7dd9-8721-4dba-aae6-985cc346795f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@aria-colindex=&quot;6&quot;]//a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4141b104-2323-4362-a48b-5c4ced6195a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>48bcb4d1-a933-4601-8cf1-f6ff38a8baaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit_a1fe7dd9-8721-4dba-aae6-985cc346795f</value>
      <webElementGuid>e43db8ca-db8a-48f1-8e68-1455694c3e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-edit</value>
      <webElementGuid>931dbbc6-6be1-4c7c-92f6-561a2840308a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>openConfigurationSlider(&quot;open_a1fe7dd9-8721-4dba-aae6-985cc346795f&quot;)</value>
      <webElementGuid>9e9b7063-94be-46a1-bc72-bbf240404a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_a1fe7dd9-8721-4dba-aae6-985cc346795f&quot;)</value>
      <webElementGuid>746adc68-1a14-4b56-8f86-d51276babe60</webElementGuid>
   </webElementProperties>
</WebElementEntity>
