<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>group</name>
   <tag></tag>
   <elementGuidId>fc0813a7-be66-4042-8873-8e917c711499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ag-cell.ag-cell-not-inline-editing.ag-cell-auto-height.grid-cell-style.ag-cell-value.ag-column-hover.ag-cell-focus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@aria-colindex=&quot;3&quot; and @role=&quot;gridcell&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>209af09f-d13a-40db-bc0e-b630b7263dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8f7c0c02-4443-4989-991d-e9bc69b71593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>137dcc37-7215-4d87-ab4f-8a21ce13f5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>f4660999-9e17-4274-86e2-392d0f024c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f3b6fe05-5647-417f-a5a8-1c50a3f0913d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>comp-id</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>797e1f65-ae28-48a0-b3b6-399ea8ecc3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>col-id</name>
      <type>Main</type>
      <value>group</value>
      <webElementGuid>75b491f4-7cf7-495b-b037-906e91724db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-cell ag-cell-not-inline-editing ag-cell-auto-height grid-cell-style ag-cell-value ag-column-hover ag-cell-focus</value>
      <webElementGuid>130aa978-149b-428a-9307-8b411865cc94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myGrid&quot;)/div[@class=&quot;ag-root-wrapper ag-layout-normal ag-ltr ag-keyboard-focus&quot;]/div[@class=&quot;ag-root-wrapper-body ag-layout-normal&quot;]/div[@class=&quot;ag-root ag-unselectable ag-layout-normal&quot;]/div[@class=&quot;ag-body-viewport ag-layout-normal ag-row-no-animation ag-has-focus&quot;]/div[@class=&quot;ag-center-cols-clipper&quot;]/div[@class=&quot;ag-center-cols-viewport&quot;]/div[@class=&quot;ag-center-cols-container&quot;]/div[@class=&quot;ag-row ag-row-even ag-row-level-0 ag-row-position-absolute ag-row-first ag-row-focus ag-row-hover&quot;]/div[@class=&quot;ag-cell ag-cell-not-inline-editing ag-cell-auto-height grid-cell-style ag-cell-value ag-column-hover ag-cell-focus&quot;]</value>
      <webElementGuid>62b636cb-f128-46d7-874b-dd583bda6478</webElementGuid>
   </webElementProperties>
</WebElementEntity>
