<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>content</name>
   <tag></tag>
   <elementGuidId>b1caece4-bdbf-4806-bf94-d993497cb85f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#msg_1680532574604</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='msg_1680532574604']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fc38a0b4-1683-4169-9102-9c0242d10517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>msg_1680532574604</value>
      <webElementGuid>a536ba80-8001-4e5d-a31f-3a007f3cb326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-danger fade in</value>
      <webElementGuid>fd687647-e683-4a72-83c4-7d8deb4e6af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>               ×Error: Please select adapter for deletion.   [9]   </value>
      <webElementGuid>5b8e9c9f-62b2-4a1c-aba4-4ffeb8a836d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msg_1680532574604&quot;)</value>
      <webElementGuid>65c451ca-662d-4bc5-af0e-01043bc4db48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='msg_1680532574604']</value>
      <webElementGuid>304e1628-a438-43fa-8b83-5a24cb5559ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='messageDiv']/div</value>
      <webElementGuid>54dd182c-f402-4385-a2d6-e3df2dfa76a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Disconnected)'])[1]/following::div[6]</value>
      <webElementGuid>d413ef7c-b038-4644-b69a-ca07a6f16538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh Rate:'])[2]/following::div[6]</value>
      <webElementGuid>44ee1d07-37ab-49a8-8527-86ccc949a0d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div</value>
      <webElementGuid>fbbb021a-2264-42a6-a635-bc6fd137e962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'msg_1680532574604' and (text() = '               ×Error: Please select adapter for deletion.   [9]   ' or . = '               ×Error: Please select adapter for deletion.   [9]   ')]</value>
      <webElementGuid>dd3c7f71-4eb4-466a-9e78-44b1e1b3eb8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
