<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cross_icon</name>
   <tag></tag>
   <elementGuidId>81f37a19-3b03-44b8-afaf-bdfe01aff0d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='msg_1680532574604']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c1baf1c5-3dbd-4728-b41f-7be73599aedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2163fce6-91a4-4cc3-94a3-c696d7b656e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>d1c61447-f2de-4e7f-88f8-b2800da325fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>3e63b9ca-1fe7-44fd-ab07-70062484e939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>9b9932ff-2101-4e68-8cfb-9d3fd7d6ec09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msg_1680532574604&quot;)/a[@class=&quot;close&quot;]</value>
      <webElementGuid>b212ac9a-9bf3-4b0f-aa8c-43035287dd50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='msg_1680532574604']/a</value>
      <webElementGuid>123d38d4-032f-42b3-8d39-f46b39d16964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'×')]</value>
      <webElementGuid>983fe5d2-3049-43f9-88ad-656fb87ae1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Disconnected)'])[1]/following::a[1]</value>
      <webElementGuid>096de983-6c0c-42ed-9f10-6e5de4f46254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error:'])[1]/preceding::a[1]</value>
      <webElementGuid>808c98d0-c214-49d6-8b06-e18ae2f9e0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[5]'])[1]/preceding::a[1]</value>
      <webElementGuid>bc3baf36-7df9-4449-ac07-e1d6133e9b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>544c4cd7-95e1-42ef-a6fc-c2bf43a07c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/a</value>
      <webElementGuid>2622fa35-cb80-430e-9950-402bfe32cd32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '×' or . = '×')]</value>
      <webElementGuid>95e4e59c-cbb7-44c2-90c8-d73016237e93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
