<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delete-action</name>
   <tag></tag>
   <elementGuidId>f0e2bfda-374c-4b59-8004-0933ff106a7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='removeAdapter(&quot;b7387524-4f85-483e-9fdb-ee58d6db1bc6&quot;, &quot;AscentAP10&quot;, &quot;Ascent AP 10 Adapter 1&quot;)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.icon-trashcan.btnAddRemoveCancel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9bd62258-6b3e-41df-a36f-aed0dc144a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>e43ab103-b659-4990-9958-08e5c968653b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-trashcan btnAddRemoveCancel</value>
      <webElementGuid>10bb801b-ac5c-4abb-8ab2-0406b848528a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-adapter-id</name>
      <type>Main</type>
      <value>open_b7387524-4f85-483e-9fdb-ee58d6db1bc6</value>
      <webElementGuid>e4ff0e02-c379-4b0a-af02-aaed7414c186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>removeAdapter(&quot;b7387524-4f85-483e-9fdb-ee58d6db1bc6&quot;, &quot;AscentAP10&quot;, &quot;Ascent AP 10 Adapter 1&quot;)</value>
      <webElementGuid>4cb215be-0174-4f5d-b605-a07c9aa38130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myGrid&quot;)/div[@class=&quot;ag-root-wrapper ag-layout-normal ag-ltr ag-keyboard-focus&quot;]/div[@class=&quot;ag-root-wrapper-body ag-layout-normal&quot;]/div[@class=&quot;ag-root ag-unselectable ag-layout-normal&quot;]/div[@class=&quot;ag-body-viewport ag-layout-normal ag-row-no-animation&quot;]/div[@class=&quot;ag-center-cols-clipper&quot;]/div[@class=&quot;ag-center-cols-viewport&quot;]/div[@class=&quot;ag-center-cols-container&quot;]/div[@class=&quot;ag-row ag-row-no-focus ag-row-even ag-row-level-0 ag-row-position-absolute ag-row-first ag-row-last ag-row-hover&quot;]/div[@class=&quot;ag-cell ag-cell-not-inline-editing ag-cell-auto-height grid-cell-style ag-cell-value ag-column-hover&quot;]/span[1]/div[@class=&quot;action-holder&quot;]/a[@class=&quot;icon-trashcan btnAddRemoveCancel&quot;]</value>
      <webElementGuid>f806bb5f-fa1e-49cc-a868-772c9cfb006f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='removeAdapter(&quot;b7387524-4f85-483e-9fdb-ee58d6db1bc6&quot;, &quot;AscentAP10&quot;, &quot;Ascent AP 10 Adapter 1&quot;)']</value>
      <webElementGuid>f90280be-118a-453a-8db2-acee75a88bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myGrid']/div/div/div/div[3]/div[2]/div/div/div/div/span/div/a[2]</value>
      <webElementGuid>710bd6a1-d77d-499a-a8ad-3384db8aa678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[11]</value>
      <webElementGuid>56c0e7fd-2e99-4c1c-8d6d-8b343d3adf1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>14fef921-d759-4345-84bb-eaa2a4b820d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>b40a0b55-c19c-4378-8b86-e0fc6fdf73af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
