<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Advanced</name>
   <tag></tag>
   <elementGuidId>81bc2088-3c0b-48fd-a260-fcf999026772</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.advanceConfigrationTab > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='configTabs']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>83cf3543-1c59-4e5f-990a-49b8005e5345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#Configuration</value>
      <webElementGuid>1322dbc2-f5fe-408f-b670-aaf1a5ab8881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>Trend</value>
      <webElementGuid>ce6a9f15-7311-4392-a7a9-89c498a9c1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>e8420669-a370-42d0-a850-8bc6eab9802f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>074cfa1c-92c4-47aa-8683-78681b06fbe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Advanced
                                                    
                                                </value>
      <webElementGuid>0bc65df6-12b4-4054-9a11-0f04eab7e02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;configTabs&quot;)/li[@class=&quot;advanceConfigrationTab&quot;]/a[1]</value>
      <webElementGuid>42c78fc4-d97e-4a15-b7a6-14ebc64ac30e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='configTabs']/li[2]/a</value>
      <webElementGuid>a837dbfd-795e-493a-85bb-4991539b7bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Advanced')]</value>
      <webElementGuid>31eff8a1-9ca8-4d96-a99d-55bce9bb624f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adapters'])[1]/following::a[1]</value>
      <webElementGuid>b69e12d0-f894-41fc-8303-ea2c559354c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Connected)'])[2]/following::a[2]</value>
      <webElementGuid>46bc0f5b-b180-453c-87a8-e51777be62f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PowerInsight'])[1]/preceding::a[2]</value>
      <webElementGuid>284f89d1-282c-49d5-9bd4-1af8f5f9ae23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Advanced']/parent::*</value>
      <webElementGuid>41b9536b-1ae0-49a7-9274-0f680bdeef03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#Configuration')]</value>
      <webElementGuid>d51b2ee4-0101-4dfc-b9f2-c4ba42fc9244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/ul/li[2]/a</value>
      <webElementGuid>503dad74-2a5a-4d46-b158-811b742aaeaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#Configuration' and (text() = '
                                                    Advanced
                                                    
                                                ' or . = '
                                                    Advanced
                                                    
                                                ')]</value>
      <webElementGuid>4292634b-3158-42c8-a816-23c37a6ae3a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
