<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Adapters</name>
   <tag></tag>
   <elementGuidId>c571a0ca-1114-4766-be25-6173b8364de8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#adapterConfigPage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='adapterConfigPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a426bd8d-04ae-47f2-9831-9c26cc7b6a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>adapterConfigPage</value>
      <webElementGuid>3b575bf5-561d-4945-96fb-424df5fe5da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#AdapterConfiguration</value>
      <webElementGuid>6beb3aa0-c306-4050-bedf-b8113e6bd124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>Trend</value>
      <webElementGuid>617cce2e-d7ae-4285-919c-10cf06e6c89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>81187393-ba77-4ab6-9fe7-5321355df4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>68338ec0-f267-4f88-947e-9e3f24012677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Adapters
                                                    
                                                </value>
      <webElementGuid>147d0b40-249f-4df4-81cf-71858a7ccb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adapterConfigPage&quot;)</value>
      <webElementGuid>eed55fb1-8a09-4dbb-8f7e-e71e2b640fd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='adapterConfigPage']</value>
      <webElementGuid>79a10b0f-ce5f-48f8-a463-f0c9acdc4689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='configTabs']/li/a</value>
      <webElementGuid>58f79118-f611-47ac-8c1c-6631c872a913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Adapters')]</value>
      <webElementGuid>8232655f-562f-4661-afc3-1da566ad0ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Connected)'])[2]/following::a[1]</value>
      <webElementGuid>958af065-2036-4803-ae6b-32d10925bab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh Rate:'])[1]/following::a[1]</value>
      <webElementGuid>5498a214-e28f-425d-9eaa-ef2caf5eddba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced'])[1]/preceding::a[1]</value>
      <webElementGuid>27f2cdb3-4793-46ec-89ce-4370c2e1480f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Adapters']/parent::*</value>
      <webElementGuid>0380e0bd-abcc-488f-9b29-f3c0865f1cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#AdapterConfiguration')]</value>
      <webElementGuid>f3b8b39a-f1f5-4121-bccf-f100340b8fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/ul/li/a</value>
      <webElementGuid>53d357bf-36fb-42c7-944f-d21f574c7549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'adapterConfigPage' and @href = '#AdapterConfiguration' and (text() = '
                                                    Adapters
                                                    
                                                ' or . = '
                                                    Adapters
                                                    
                                                ')]</value>
      <webElementGuid>77835158-2f71-427f-9af0-15acb63ffa50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
