<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save Configurations</name>
   <tag></tag>
   <elementGuidId>272822c1-e474-4ddd-bfab-825084d27346</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSaveConfig</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSaveConfig']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>99ae9ecb-1924-4484-9181-8e30ef7fa75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading-text</name>
      <type>Main</type>
      <value>Saving..</value>
      <webElementGuid>f300e699-66fb-4116-b007-32fa2b53a7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-teach</value>
      <webElementGuid>decb676f-aefe-4ff1-ab0f-8d2288889cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSaveConfig</value>
      <webElementGuid>8c88cc9f-898e-4bf6-adbc-1ed1dff0aedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ccdd0f11-c29d-4dda-91a5-4eb3f327a677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save Configurations</value>
      <webElementGuid>2eb137ad-53ad-45d9-a50a-35489567d456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;configTabs&quot;)/li[4]/button[@id=&quot;btnSaveConfig&quot;]</value>
      <webElementGuid>f7ce80a7-8aa6-452a-9073-5c308b60f2cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnSaveConfig']</value>
      <webElementGuid>8f2166d6-1ffb-4079-9150-808fa14681ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='configTabs']/li[4]/button</value>
      <webElementGuid>1885fa25-c0be-43a7-a01f-d47e73ea1324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Part Number'])[1]/following::button[1]</value>
      <webElementGuid>1854a215-216b-4f91-9d71-57cbf1a340e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number'])[1]/following::button[1]</value>
      <webElementGuid>40040fa6-e17b-4b19-89d0-20f714648e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General'])[1]/preceding::button[1]</value>
      <webElementGuid>c7372672-0212-4b7c-b01d-5273d7349523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publishers'])[1]/preceding::button[1]</value>
      <webElementGuid>0f0cfcf0-b796-4445-b831-d35a69d49b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save Configurations']/parent::*</value>
      <webElementGuid>41512a7c-f1ec-4d07-ba59-40e04bb1136e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/button</value>
      <webElementGuid>1a6b9daf-90f3-4c89-87f2-1cbffbbc85d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnSaveConfig' and @type = 'submit' and (text() = 'Save Configurations' or . = 'Save Configurations')]</value>
      <webElementGuid>a1e3b346-73c0-4110-a477-d4ffcb82e62d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
