<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAdvancedOptions</name>
   <tag></tag>
   <elementGuidId>e7f28152-6c65-4fc4-a1e3-f059304fcc6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Advanced options&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='sidebar']/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6f2040a4-65c7-49bd-ad29-9e9ba807a189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Advanced options</value>
      <webElementGuid>f80cf810-dc99-43d8-a2f8-7c423eec5c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/edgeui/settings</value>
      <webElementGuid>b6063c39-c90d-4b62-a5ab-fbb9a7bda36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Advanced Options</value>
      <webElementGuid>e76dc835-eaec-49f9-9737-86362a40e68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/li[3]/a[1]</value>
      <webElementGuid>01c0269e-2048-40da-9164-5783572b6fff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebar']/li[3]/a</value>
      <webElementGuid>c4585287-4b4f-4c44-9d0a-1bc9d00e294c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[1]</value>
      <webElementGuid>17e990c8-80a5-48dc-b307-d38d981e4132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License Options'])[1]/preceding::a[1]</value>
      <webElementGuid>3e1cb257-2318-46df-8c0f-230e57a59ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/edgeui/settings')]</value>
      <webElementGuid>f98540ca-6001-4dec-93ed-2196a55dd6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>b64c797b-b31d-4461-b898-b3e211889521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Advanced options' and @href = '/edgeui/settings' and (text() = 'Advanced Options' or . = 'Advanced Options')]</value>
      <webElementGuid>3d41622d-2f88-4f23-82a9-355d61b40b93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
