<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDashboard</name>
   <tag></tag>
   <elementGuidId>9da9b787-c4ec-488d-aba7-0b804acba002</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.sidebar-brand.active > #menu-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='menu-toggle'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>67acd833-7074-4243-abe8-ba407f8acfa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>fe490f2c-cb0b-45d4-bd8d-3a7a4acc26dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-toggle</value>
      <webElementGuid>2dfdf2f3-57ec-4659-a944-e12adb7deed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/edgeui/dashboard</value>
      <webElementGuid>c9d2733e-8963-4018-b7db-5b4abd403074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>9410ea1b-af94-4b81-b457-ad46021b320f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/li[@class=&quot;sidebar-brand active&quot;]/a[@id=&quot;menu-toggle&quot;]</value>
      <webElementGuid>31c47710-80bf-411d-bf84-648671a53c25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='menu-toggle'])[2]</value>
      <webElementGuid>faaac85e-f7a7-42cf-8eb5-f7e6991d3e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebar']/li[2]/a</value>
      <webElementGuid>aaec2c4c-ecfa-4057-9006-53db50eadac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Options'])[1]/preceding::a[1]</value>
      <webElementGuid>d17bc856-9416-42f2-b1e5-2b17674eba39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/edgeui/dashboard')]</value>
      <webElementGuid>fc0e6dbb-25af-4167-aa6e-d43970aaeca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>53efd81b-ba44-4cab-9dc9-b05dd5bc7481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Dashboard' and @id = 'menu-toggle' and @href = '/edgeui/dashboard' and (text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>96226097-6f4d-4b79-b340-c590617bef7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
