<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DisableAll</name>
   <tag></tag>
   <elementGuidId>131ea005-2b43-4e0a-bdf1-aaf1bf314712</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnDisableAdapter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnDisableAdapter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c11808f0-6306-4558-8795-8525cfe0f859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn open-ExportConfiguration</value>
      <webElementGuid>15cf49fe-cb52-47ae-b724-3a045a913dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDisableAdapter</value>
      <webElementGuid>bbfc65ae-3a28-4d96-bb99-c08866ab2810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b898d118-3fff-4528-8855-f2a2cd3cb24e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>c3f3a5cb-8b26-45c2-9b45-66c3ef6b68e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Disable</value>
      <webElementGuid>292be32a-fcbf-457b-bc56-18e0e5a7c513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnDisableAdapter&quot;)</value>
      <webElementGuid>805baba9-7617-4b12-91eb-179a9cdb8046</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnDisableAdapter']</value>
      <webElementGuid>971d3458-8699-4482-bcae-99764598b4a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AdapterConfiguration']/div/div/button[4]</value>
      <webElementGuid>3627b31d-80b1-43b0-8159-5328eb8e6823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable'])[1]/following::button[1]</value>
      <webElementGuid>cb106ffe-d496-4b67-a6ff-4e245c02584e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::button[2]</value>
      <webElementGuid>ead20d10-6fc5-4131-a1aa-c8cb28ced556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of records per page:'])[1]/preceding::button[1]</value>
      <webElementGuid>46b8404b-1232-4154-8bc6-cfedc4e5fff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adapter Name'])[2]/preceding::button[1]</value>
      <webElementGuid>cc33107a-d8cd-4dc9-a315-a6e37ea4b50a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Disable']/parent::*</value>
      <webElementGuid>50b22545-1c0c-474f-b7ea-7196e02d4338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>ed5e4d6f-d0e5-46af-910b-c6083036e9c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnDisableAdapter' and @type = 'button' and (text() = 'Disable' or . = 'Disable')]</value>
      <webElementGuid>68d04fa2-9cc1-4f7d-bc1f-3155b1a6d281</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
