<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_EnableAll</name>
   <tag></tag>
   <elementGuidId>c49deb68-0522-464b-9817-a532787b32a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnEnableAdapter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnEnableAdapter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>32a73a5d-90c5-4513-b56b-9e0eb531eb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn open-ExportConfiguration</value>
      <webElementGuid>e3e18f25-fe88-475c-aad8-98fca6609d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEnableAdapter</value>
      <webElementGuid>aaff0788-4309-4c7e-87c8-118995fbaf3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6a95c8e8-6215-4e97-b05a-20ae3383f345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>4a7a4158-685d-4c2f-adab-047ae87d88e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enable</value>
      <webElementGuid>34a625d5-cc59-4bb7-9c24-2a6f46120e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnEnableAdapter&quot;)</value>
      <webElementGuid>337c933a-f9d3-4e7f-bdae-618dc9be5ef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnEnableAdapter']</value>
      <webElementGuid>b7095d28-4664-4ce3-8a9c-63b906ea03e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AdapterConfiguration']/div/div/button[3]</value>
      <webElementGuid>d60c4af6-45f0-43e6-9380-7641c291b29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::button[1]</value>
      <webElementGuid>9d7e2b39-197e-42c8-85b5-15a218fb486f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::button[2]</value>
      <webElementGuid>6d6f1d93-7d0a-4814-a489-4d7507249d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disable'])[1]/preceding::button[1]</value>
      <webElementGuid>feaa8b84-a68e-4c02-b8b2-08797dd4d116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of records per page:'])[1]/preceding::button[2]</value>
      <webElementGuid>e63e9969-6b53-4362-8416-4ff0c27355e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enable']/parent::*</value>
      <webElementGuid>9f6cd2e6-d620-4d82-b040-c4eb855cab9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>fdc67356-471c-48c9-aa99-27d2ca7be42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnEnableAdapter' and @type = 'button' and (text() = 'Enable' or . = 'Enable')]</value>
      <webElementGuid>8a80f2ef-c1b3-476c-96ee-2be51fad9920</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
