<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header</name>
   <tag></tag>
   <elementGuidId>9f1ec473-4a85-4f9e-a64b-c09b619b8799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmationDialogHeader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='confirmationDialogHeader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>f30bc4b8-fefb-49d2-b231-85ceec116330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>9347df36-cd5f-4d7d-a906-aae364814cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmationDialogHeader</value>
      <webElementGuid>c0658478-91b4-46d3-bf4a-cc7c1bb0670c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete Confirmation - Adam Adapter 1</value>
      <webElementGuid>d69fad16-52bb-4110-bf59-c9466b8d3120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmationDialogHeader&quot;)</value>
      <webElementGuid>70632aef-f88d-41c9-a13e-e06f94614cda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='confirmationDialogHeader']</value>
      <webElementGuid>8212fdfc-b025-4900-bb4d-26c896e15250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deleteConfirmationDialog']/div/div/div/h4</value>
      <webElementGuid>3c811b8c-fa7e-4640-b4f9-d41d129b4407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Menu'])[1]/following::h4[1]</value>
      <webElementGuid>38853e65-a2fa-4356-8649-cdff95f203d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/following::h4[1]</value>
      <webElementGuid>bf031063-1758-4a5f-bfae-ff43d71d35f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adam Adapter 1'])[3]/preceding::h4[1]</value>
      <webElementGuid>72dabfb2-6475-412f-824a-e12ad5a81a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::h4[1]</value>
      <webElementGuid>ff7f6699-7ff8-4dbd-9074-7f5548dbd508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete Confirmation - Adam Adapter 1']/parent::*</value>
      <webElementGuid>083d5cbb-1f14-4ee8-9cd2-61cc82380763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/h4</value>
      <webElementGuid>5fa6e2f3-83c9-483b-a484-b4a859817f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'confirmationDialogHeader' and (text() = 'Delete Confirmation - Adam Adapter 1' or . = 'Delete Confirmation - Adam Adapter 1')]</value>
      <webElementGuid>17464711-521c-416f-8a62-081fbe6badbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
