<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_LastRestartedValue</name>
   <tag></tag>
   <elementGuidId>a3e8f2e2-4c08-49b2-aa41-2105744876e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.status-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[1]//span[@class=&quot;status-info&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ddd7faca-9c21-4dd0-961b-2db2ddc6ba0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>status-info</value>
      <webElementGuid>d1ec0711-e8d2-43ff-be37-662f567da20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>09/03/2023 3:04:09 PM GMT+5</value>
      <webElementGuid>dc292f87-ffea-474e-b581-d169ea164592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;main-content&quot;]/div[@class=&quot;.container-fluid&quot;]/app-stats[1]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;status-header&quot;]/ul[1]/li[1]/span[@class=&quot;status-info&quot;]</value>
      <webElementGuid>3f476688-7097-4a02-b63f-7e93c656ec73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//li[1]//span[@class=&quot;status-info&quot;]</value>
      <webElementGuid>c13a555a-1abc-46ea-9d96-410b74141e0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
