<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SerialNumberValue</name>
   <tag></tag>
   <elementGuidId>b276dc39-7d6e-485e-bceb-f82634712c99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[4]//span[@class=&quot;status-info&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>63390fc5-33da-4cb6-bdca-184094e0fdd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>status-info</value>
      <webElementGuid>4af3aeac-c42c-4775-b25f-309824dd3c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1028812348</value>
      <webElementGuid>7c2d84a0-aecb-42cc-91e2-2419957721c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;main-content&quot;]/div[@class=&quot;.container-fluid&quot;]/app-stats[1]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;status-header&quot;]/ul[1]/li[4]/span[@class=&quot;status-info&quot;]</value>
      <webElementGuid>25ff7e35-1b6d-4065-be55-0c0ce5f57632</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//li[4]//span[@class=&quot;status-info&quot;]</value>
      <webElementGuid>e84b26e4-3426-4bc6-bb02-971e968731f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
