<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AppVersionValue</name>
   <tag></tag>
   <elementGuidId>d6f4c8f7-3d69-40aa-ad0e-d7ef79e68c48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[3]//span[@class=&quot;status-info&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7f2d48b9-2ec0-468e-92b4-2f10290f6810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>status-info</value>
      <webElementGuid>c161406d-010e-4fb3-84ac-0e827daa542a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>v2.4.1 (build: 403101b_13022023)</value>
      <webElementGuid>cd32f512-acf2-4470-9896-ccc155d4737a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;main-content&quot;]/div[@class=&quot;.container-fluid&quot;]/app-stats[1]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;status-header&quot;]/ul[1]/li[3]/span[@class=&quot;status-info&quot;]</value>
      <webElementGuid>437f62e1-ee8f-4868-a7fe-9df08b990f51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//li[3]//span[@class=&quot;status-info&quot;]</value>
      <webElementGuid>e9e0491a-49e7-41b1-8c38-5c322db8dd89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
