<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_TemperaturValue</name>
   <tag></tag>
   <elementGuidId>d1f51e23-5922-46a1-a82b-323c436968e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='temperatureCount']//*[name()='svg']//*[local-name()='tspan'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>64631cff-d97d-4ef1-9a24-a05aba70e3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>275db216-103b-4fdc-b5a8-d7b649f75268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0.0</value>
      <webElementGuid>40bec6ce-9878-4c7e-acf2-203332a6fb18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;temperatureCount&quot;)/svg[1]/text[2]/tspan[1]</value>
      <webElementGuid>3faa2156-394b-4156-a8c5-3e40d2f3915e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(//div[@id='temperatureCount']//*[name()='svg']//*[local-name()='tspan'])[2]</value>
      <webElementGuid>948262e6-c7fd-4806-824c-33c2884efb80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
