<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_StorageHeading</name>
   <tag></tag>
   <elementGuidId>ec5be867-8edb-4d36-8bb5-f509bde11acb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#availableStorage > svg > text > tspan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='availableStorage']//*[name()='svg']//*[local-name()='tspan'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>46e8dfe0-b4fa-44b0-9cad-3d8a1a06338f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>84af9b29-3ed9-4514-97c5-52784066dd24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Storage</value>
      <webElementGuid>c4dc9b59-2846-442c-97de-42c400a1444d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;availableStorage&quot;)/svg[1]/text[1]/tspan[1]</value>
      <webElementGuid>76390043-9e56-4940-a492-bfd4d39382aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(//div[@id='availableStorage']//*[name()='svg']//*[local-name()='tspan'])[1]</value>
      <webElementGuid>4c928a7b-9930-4a9f-818c-8229a9986b82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
