<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_TemperatureValueType</name>
   <tag></tag>
   <elementGuidId>066420a9-33d7-4fcf-9fbe-365d7e4000df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='temperatureCount']//*[name()='svg']//*[local-name()='tspan'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>7494af29-116d-4b50-ae75-e669c028396e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>808d2451-4c18-4b35-94f3-c5910da42c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>°C</value>
      <webElementGuid>8236b589-9a30-4f27-8eea-02931f109616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;temperatureCount&quot;)/svg[1]/text[3]/tspan[1]</value>
      <webElementGuid>9fc20c20-02e7-4883-b43a-3226757677d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(//div[@id='temperatureCount']//*[name()='svg']//*[local-name()='tspan'])[3]</value>
      <webElementGuid>c5533c52-72c5-43c3-b85a-262054c1df74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
