<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_RAMHeading</name>
   <tag></tag>
   <elementGuidId>a434c707-846f-4227-a714-11bf30cf6b42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#availableRAM > svg > text > tspan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='availableRAM']//*[name()='svg']//*[local-name()='tspan'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>d39a7691-f8f6-4a24-a434-9ed2e6df6753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8805bd2b-45ab-472f-b5b0-20601db1daa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RAM</value>
      <webElementGuid>3dcbf35c-b4c0-4913-a626-00c70fe2e6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;availableRAM&quot;)/svg[1]/text[1]/tspan[1]</value>
      <webElementGuid>8651d5e5-a88c-4520-817e-80623bd08812</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(//div[@id='availableRAM']//*[name()='svg']//*[local-name()='tspan'])[1]</value>
      <webElementGuid>1d2b0a4c-1d24-4598-a215-1e94422716c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
