<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_RAMValueType</name>
   <tag></tag>
   <elementGuidId>40ef5621-9a01-41c2-8ed4-6fd7435252ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='availableRAM']//*[name()='svg']//*[local-name()='tspan'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>efb84c67-1879-421f-93f6-fbba37fcc8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>423341d4-e12e-4cc6-a7e8-7bf675a8d0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GB Used</value>
      <webElementGuid>86882cba-cf87-4d3f-b82c-cee6d09a42ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;availableRAM&quot;)/svg[1]/text[3]/tspan[1]</value>
      <webElementGuid>908c8b50-df82-4d9c-b97e-417c307e9b26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(//div[@id='availableRAM']//*[name()='svg']//*[local-name()='tspan'])[3]</value>
      <webElementGuid>f9f18d0f-d306-4d7c-91f7-c0b42212477a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
