<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_Temperature_StartingValue</name>
   <tag></tag>
   <elementGuidId>dbdf9678-4ff9-4bb1-9290-04af5b764c3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='temperatureCount']//*[name()='svg']//*[local-name()='tspan'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>250a60a9-33f5-456e-977e-949e07ccafb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>26ab6e4d-3a0c-49ee-8df9-dee6067c8896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c6f24372-6210-4de2-b1c8-7ed8d09b5a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;temperatureCount&quot;)/svg[1]/text[4]/tspan[1]</value>
      <webElementGuid>e8bc9b12-6420-46ad-b1ba-cbe44a46a86a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>(//div[@id='temperatureCount']//*[name()='svg']//*[local-name()='tspan'])[4]</value>
      <webElementGuid>742101a3-e499-40c7-8c52-ec682e3096b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
