<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_CPUHeading</name>
   <tag></tag>
   <elementGuidId>715b4b4f-cc3b-45ed-9976-8e911be1b0e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tspan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='cpuUsageCount']//*[name()='svg']//*[local-name()='tspan'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>4f9de94a-750c-4825-b5ec-b696276d2a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a5c6db90-7cec-4cc5-96f0-027fb420d2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CPU</value>
      <webElementGuid>23150f3f-f0f5-44f0-a4c5-4e34d3cf9da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpuUsageCount&quot;)/svg[1]/text[1]/tspan[1]</value>
      <webElementGuid>9f395129-7f5c-4414-9627-afb4fef882d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(//div[@id='cpuUsageCount']//*[name()='svg']//*[local-name()='tspan'])[1]</value>
      <webElementGuid>65775164-c32d-44d4-a055-301cf726dd18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
