<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_RAM_EndingValue</name>
   <tag></tag>
   <elementGuidId>428229d3-1d4c-4804-b6f0-ab82a8f3811a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='availableRAM']//*[name()='svg']//*[local-name()='tspan'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>5ef9b180-0c40-44db-9603-f609dc1f27eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>340029d8-4c30-4690-9259-8fce3634e2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7.95</value>
      <webElementGuid>f48abe97-2509-4aea-aebe-b436139747d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;availableRAM&quot;)/svg[1]/text[5]/tspan[1]</value>
      <webElementGuid>e72bf425-b457-4c15-91d8-47e7a6900c03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(//div[@id='availableRAM']//*[name()='svg']//*[local-name()='tspan'])[5]</value>
      <webElementGuid>a69016b1-2422-497d-81c1-c3c4d36597ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
