<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_CPU_StartingValue</name>
   <tag></tag>
   <elementGuidId>4b9415b1-a21d-4a9b-8944-7d5a9af9b24c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='cpuUsageCount']//*[name()='svg']//*[local-name()='tspan'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>3eef1aa0-1d66-481b-b591-8c6457d256d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eb5ea0de-7ceb-4a37-a16d-d52110c3d2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e5f801c9-8867-420e-98a3-2377859d0fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpuUsageCount&quot;)/svg[1]/text[4]/tspan[1]</value>
      <webElementGuid>1dab62ca-4699-49c5-a86e-e31adef9dea1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(//div[@id='cpuUsageCount']//*[name()='svg']//*[local-name()='tspan'])[4]</value>
      <webElementGuid>de3717f6-e09b-434f-8a09-1db49016d1bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
