<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_StorageValue</name>
   <tag></tag>
   <elementGuidId>fe0beb60-7419-487f-85aa-a471d73c9635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='availableStorage']//*[name()='svg']//*[local-name()='tspan'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>65e7cc37-ca4b-43ec-871c-2ff7d4b0d741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2f989745-dbe8-44cc-8834-e621e0823fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>61.6</value>
      <webElementGuid>288335a5-c748-4057-86eb-1e58acbd787d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;availableStorage&quot;)/svg[1]/text[2]/tspan[1]</value>
      <webElementGuid>e0d848a2-ff87-4ae2-a513-8b35f5340463</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(//div[@id='availableStorage']//*[name()='svg']//*[local-name()='tspan'])[2]</value>
      <webElementGuid>52be2e16-6e8f-4036-a620-7fabdd446366</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
