<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_CPU_EndingValue</name>
   <tag></tag>
   <elementGuidId>ddc33eea-a75f-437c-acbd-0113b1908db2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='cpuUsageCount']//*[name()='svg']//*[local-name()='tspan'])[5]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>4f851839-3c0f-4ccc-a97c-09d3bac82230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cf5b9c87-bb12-492e-97ab-c4e43a8868cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>029d9afd-05be-41a4-951b-d68324ed2ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpuUsageCount&quot;)/svg[1]/text[5]/tspan[1]</value>
      <webElementGuid>e67c9d90-9626-4c0e-9e1d-41a9ea3ccefa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(//div[@id='cpuUsageCount']//*[name()='svg']//*[local-name()='tspan'])[5]</value>
      <webElementGuid>a90dd5dc-7e2d-48a3-ba8f-1aa03cacd2f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
