<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_CPUValue</name>
   <tag></tag>
   <elementGuidId>02392a99-deca-4ec9-8846-a7d722fb18bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='cpuUsageCount']//*[name()='svg']//*[local-name()='tspan'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>ae241b00-bc50-456c-bf5a-ac03221677be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6982162d-b84d-4ea6-9c0c-1c58ef9de14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>22.7</value>
      <webElementGuid>ee57a6b6-7836-4c45-9849-a60c4234b313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpuUsageCount&quot;)/svg[1]/text[2]/tspan[1]</value>
      <webElementGuid>31448f34-5799-4b40-b4a7-ef926cb5b239</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(//div[@id='cpuUsageCount']//*[name()='svg']//*[local-name()='tspan'])[2]</value>
      <webElementGuid>c1366b24-9ad9-41a5-93b9-1e81f2f66ee0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
