<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_CPUValueType</name>
   <tag></tag>
   <elementGuidId>c968d1c9-ee5a-47e0-8c23-e8d05d157092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='cpuUsageCount']//*[name()='svg']//*[local-name()='tspan'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>134c3939-57c1-4413-90df-3fd972005f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8acac0ce-1c04-47cb-856e-831c86b4354c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>%</value>
      <webElementGuid>3b27c132-5c2e-4846-bb51-05ccaf3a034d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpuUsageCount&quot;)/svg[1]/text[3]/tspan[1]</value>
      <webElementGuid>e5c84737-c085-41b3-872e-21712b4762aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(//div[@id='cpuUsageCount']//*[name()='svg']//*[local-name()='tspan'])[3]</value>
      <webElementGuid>86badcce-831e-4df7-bc0e-bfa254a990b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
