<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_Storage_StartingValue</name>
   <tag></tag>
   <elementGuidId>4caa8756-3ad8-4e37-b151-0229e630b7f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='availableStorage']//*[name()='svg']//*[local-name()='tspan'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>d8163494-f889-4794-b906-b8f23d7c0bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>387a86b7-7ae9-4d79-a5f9-ec062f8b50bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4bffbacf-29a9-4633-b8e9-a8357ad23b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;availableStorage&quot;)/svg[1]/text[4]/tspan[1]</value>
      <webElementGuid>58427852-9435-44b3-91aa-8ef3cab770fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>(//div[@id='availableStorage']//*[name()='svg']//*[local-name()='tspan'])[4]</value>
      <webElementGuid>373ab788-aef9-4b2e-bc21-f8e7668fe0da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
