<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_RAM_StartingValue</name>
   <tag></tag>
   <elementGuidId>8214e52c-dde7-4d84-bdb0-a33aece7d60e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='availableRAM']//*[name()='svg']//*[local-name()='tspan'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>d49dd91d-1423-4df6-80b5-2ee0e1d5a674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>03b3a3f8-0bd2-4cde-b0f6-def4b17b2325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e49df787-0869-4ba6-9a22-40780f460310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;availableRAM&quot;)/svg[1]/text[4]/tspan[1]</value>
      <webElementGuid>dab00049-df72-4012-8c8f-833dc3b5bfd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>(//div[@id='availableRAM']//*[name()='svg']//*[local-name()='tspan'])[4]</value>
      <webElementGuid>b7e84e38-1c6c-4ce0-9fdc-ce7fc95535c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
