<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_Temperature_EndingValue</name>
   <tag></tag>
   <elementGuidId>56eeda43-9ca3-4151-a3b1-3c98cf4ef58e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='temperatureCount']//*[name()='svg']//*[local-name()='tspan'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>274732f9-7358-4a2b-a5da-9be2b3146e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>74b2278a-0db3-4ebf-9f89-ee4bbe4aa969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c01c548d-714d-45a2-9c2b-004b9b5fdb5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;temperatureCount&quot;)/svg[1]/text[5]/tspan[1]</value>
      <webElementGuid>d8bc3c82-416f-4ecb-b44f-3f08511d6727</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>(//div[@id='temperatureCount']//*[name()='svg']//*[local-name()='tspan'])[5]</value>
      <webElementGuid>b54bf9c3-bbcd-4bd4-a446-e617a9d41da7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
