<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_RAMValue</name>
   <tag></tag>
   <elementGuidId>b9811c16-24b2-4be7-b8b5-925c85c48904</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='availableRAM']//*[name()='svg']//*[local-name()='tspan'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>1e11d7c4-1560-47d6-965d-ac880ab9936c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>07b17959-9c67-466b-9208-e940a9adde3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2.0</value>
      <webElementGuid>004b1f38-b20c-4859-ba5f-31eed2d1030a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;availableRAM&quot;)/svg[1]/text[2]/tspan[1]</value>
      <webElementGuid>6ea1b6a9-13c0-43a1-9672-7874fce030ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(//div[@id='availableRAM']//*[name()='svg']//*[local-name()='tspan'])[2]</value>
      <webElementGuid>d3c36740-ca7b-4f2b-a539-4e2bab040847</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
