<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_StorageValueType</name>
   <tag></tag>
   <elementGuidId>6bac3203-8eb0-471b-9ad8-1a7b2b8fd948</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='availableStorage']//*[name()='svg']//*[local-name()='tspan'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>368224bd-23a2-42b4-afa8-11e50ae8035f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>afa5045f-c4fe-46f2-af48-1d5480bef29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GB Used</value>
      <webElementGuid>e71b02ff-5878-4889-a09e-30883acb8f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;availableStorage&quot;)/svg[1]/text[3]/tspan[1]</value>
      <webElementGuid>0f064af9-e09e-42a5-af32-13d63aea136e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>(//div[@id='availableStorage']//*[name()='svg']//*[local-name()='tspan'])[3]</value>
      <webElementGuid>c214cfe9-19b7-4764-b996-8622e791942c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
