<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_Storage_EndingValue</name>
   <tag></tag>
   <elementGuidId>9e12f977-e06c-4983-bc47-80854a0524d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='availableStorage']//*[name()='svg']//*[local-name()='tspan'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>27bba414-7b42-40bf-be01-4be8d87294db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8a5b9967-9d3e-4ade-a993-c20e1939d74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>491.1</value>
      <webElementGuid>8a7d5290-514b-42af-a3dc-d6bebba544b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;availableStorage&quot;)/svg[1]/text[5]/tspan[1]</value>
      <webElementGuid>10cf772d-a50d-4988-aa8a-45c84045dd79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(//div[@id='availableStorage']//*[name()='svg']//*[local-name()='tspan'])[5]</value>
      <webElementGuid>24b1aaaa-edaf-4653-8b85-c38151663870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
