<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Device</name>
   <tag></tag>
   <elementGuidId>1a44f3a6-1e90-4317-8484-29f34fb6d190</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal-body > div > div.holder > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalAddRemoveAdapterConfiguration']/div/div/div[2]/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d9ddf27e-adce-4eb1-be20-3990b9d128ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Device:</value>
      <webElementGuid>e0cc5b8e-6ed6-4c14-a27d-65af25feb64f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalAddRemoveAdapterConfiguration&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[1]/div[@class=&quot;holder&quot;]/label[1]</value>
      <webElementGuid>131c5890-364d-449a-a77c-921e70d12c20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalAddRemoveAdapterConfiguration']/div/div/div[2]/div/div/label</value>
      <webElementGuid>6fc7eeaf-4e94-4294-82be-be67429da9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Adapter'])[1]/following::label[1]</value>
      <webElementGuid>c65f392a-b540-446c-bb4a-49e8d0cc903b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Adapter'])[1]/following::label[2]</value>
      <webElementGuid>f5b2501b-aabc-4bd5-aa7e-379414e4ec64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adam6017'])[2]/preceding::label[1]</value>
      <webElementGuid>6dcdee7c-9f8e-420c-abea-faa6746d183c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[1]/preceding::label[1]</value>
      <webElementGuid>126e7b2f-293b-49aa-9488-69a9425a7155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Device:']/parent::*</value>
      <webElementGuid>e0dc3021-0dec-420e-8aed-b6665a3a16de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div/label</value>
      <webElementGuid>816e40db-edb3-4092-8cd9-22291bb33b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Device:' or . = 'Device:')]</value>
      <webElementGuid>6c93c172-6afa-4a84-a67f-07df936ccba7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
