<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_No</name>
   <tag></tag>
   <elementGuidId>e3594538-89ca-4542-bb2f-2872f8ef9919</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deleteAllBtnNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='deleteAllBtnNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3045a635-4e8c-4749-9e38-84e25f170331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-teach</value>
      <webElementGuid>1b98dacf-82d4-430d-84af-5fd8c9ac33e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deleteAllBtnNo</value>
      <webElementGuid>97789f60-e3d6-4911-ad10-e7cd8dbe5dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>89fabbaa-2462-498d-b225-4a1fa7267685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deleteAllBtnNo&quot;)</value>
      <webElementGuid>ae4f72de-1e1a-442e-951b-38fa495b49b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='deleteAllBtnNo']</value>
      <webElementGuid>924695fa-36af-4e61-8a9e-65857107b687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deleteAllConfirmationDialog']/div/div/div[3]/button[2]</value>
      <webElementGuid>ca546341-a2fc-4b85-b0bb-87650bc96b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[2]/following::button[1]</value>
      <webElementGuid>53de2f74-3e91-4aea-a2e2-75ba482293fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Confirmation'])[1]/following::button[2]</value>
      <webElementGuid>87690a39-7393-4924-8785-11bcadc6115a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable/Disable Adapter'])[1]/preceding::button[1]</value>
      <webElementGuid>babd3418-b58c-4257-816d-9186dcd4f390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable All Adapters'])[1]/preceding::button[1]</value>
      <webElementGuid>a6e6d2cc-6172-4cf4-bc66-3482319e5a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/button[2]</value>
      <webElementGuid>57c3145b-af3b-4933-9e38-02f740a3f46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'deleteAllBtnNo' and (text() = 'No' or . = 'No')]</value>
      <webElementGuid>711e2fa2-b5ea-4923-87d5-ebc342d1d460</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
