<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Delete Confirmation</name>
   <tag></tag>
   <elementGuidId>b89f6575-6458-4aae-94e2-53bf6b05d029</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmationDialogHeaderAll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='confirmationDialogHeaderAll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>13669a11-d614-4d26-b911-597ea3a6224a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>fd434fec-41c3-4dc4-a2ed-4951ed5dc84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmationDialogHeaderAll</value>
      <webElementGuid>9a28bd1e-51d6-46ac-9608-0785f0da45c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete Confirmation</value>
      <webElementGuid>310bb7c2-6d12-4674-b742-5f310ecdcfdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmationDialogHeaderAll&quot;)</value>
      <webElementGuid>2e04254b-cc0c-4f88-8dca-09582e036ef9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='confirmationDialogHeaderAll']</value>
      <webElementGuid>93f500d4-2059-42ae-a62a-0810c6bed411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deleteAllConfirmationDialog']/div/div/div/h4</value>
      <webElementGuid>e9a0b491-b628-4dcc-85e9-b90dd6186c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::h4[1]</value>
      <webElementGuid>30780b3f-5ad1-450e-9754-ebf9af7c545b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/following::h4[1]</value>
      <webElementGuid>d206db5f-c57f-4b7c-aba2-dc98dfcd7821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[2]/preceding::h4[1]</value>
      <webElementGuid>18924874-8ad4-4b38-8ff6-c1d2b95e2746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/preceding::h4[1]</value>
      <webElementGuid>bb27e814-292f-4d04-b7bd-3fa1d224206c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete Confirmation']/parent::*</value>
      <webElementGuid>aee4e8cd-6b7e-43e1-9df9-896d6ce9422d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/h4</value>
      <webElementGuid>b5c2aefb-d35b-4ce4-bab3-21517b1e94e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'confirmationDialogHeaderAll' and (text() = 'Delete Confirmation' or . = 'Delete Confirmation')]</value>
      <webElementGuid>43e296b4-6f4e-47f5-837a-aaa4660eaff9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
