<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_About</name>
   <tag></tag>
   <elementGuidId>a7333687-aabe-4f3b-9d02-e50a2b5209df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.about-app</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@class=&quot;about-area&quot;] | //li[@class=&quot;about-area active&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c3917eef-4bf4-4ce9-92b9-89e0047cbdf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>about-app</value>
      <webElementGuid>99d11afe-1452-4ece-9db0-6ce67de0acdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#AboutApplication</value>
      <webElementGuid>415560b9-43e6-4766-ade8-92f8a945c491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>Trend</value>
      <webElementGuid>ba1bc268-c039-455b-b779-f8c4e8a73d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>198f5f45-e5f2-46c2-bcf0-493defc0d77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>1a534c91-188d-48bd-ba78-430a9c54647f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    
                                                    About
                                                </value>
      <webElementGuid>3fee60fa-a422-47f6-8254-8f94f6da7184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;configTabs&quot;)/li[@class=&quot;about-area&quot;]/a[@class=&quot;about-app&quot;]</value>
      <webElementGuid>54de0fcb-7de1-477e-9d18-311e7aacafdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@class=&quot;about-area&quot;] | //li[@class=&quot;about-area active&quot;]</value>
      <webElementGuid>6fe58243-3b4d-47c5-934e-68b325631a9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
