<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_serialNumInfo</name>
   <tag></tag>
   <elementGuidId>94636f70-712e-42df-b099-8570e09f7369</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#appSerialNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='appSerialNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f8e19947-e837-402d-9916-e8132fca7d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appSerialNumber</value>
      <webElementGuid>a902c096-da35-4e0a-94b6-2426ddf1f456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1028812348</value>
      <webElementGuid>7383fc3a-4ef4-4193-bd22-8fb52f3d8f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appSerialNumber&quot;)</value>
      <webElementGuid>bdad1360-80c9-4cc7-8ea0-da87f94103f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='appSerialNumber']</value>
      <webElementGuid>07452357-bbfe-4765-8b75-8d9f5372aef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AboutApplication']/div[2]/span</value>
      <webElementGuid>760c3ac1-91db-4e90-ac06-af39e7cb3078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number'])[1]/following::span[1]</value>
      <webElementGuid>e06bfa22-b009-4e8d-8ade-b16ccdf1c52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v2.4.2 (build: 44de479_03032023)'])[1]/following::span[1]</value>
      <webElementGuid>08ef3723-75b9-4f3f-b237-4837643a6188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Part Number'])[1]/preceding::span[1]</value>
      <webElementGuid>5f44ba0a-8c28-45e5-9d35-609d1ee94d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Configurations'])[1]/preceding::span[2]</value>
      <webElementGuid>5335e20f-fd7e-4ad6-a31e-fb6fda4b0c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1028812348']/parent::*</value>
      <webElementGuid>df90d91f-c246-421b-b89c-4fdfde84299c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>3e4d469b-bc60-4c0b-8f80-98ef0fb7379a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'appSerialNumber' and (text() = '1028812348' or . = '1028812348')]</value>
      <webElementGuid>279afb4a-2340-4156-ad9d-18f4b0bf23a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
