<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_buildInfo</name>
   <tag></tag>
   <elementGuidId>be72f36a-40a6-4ad6-b1ed-808b0a0d95e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#appVersion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='appVersion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>96cd22b2-e59d-407e-b7a0-0893c8ae9bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appVersion</value>
      <webElementGuid>e51d6351-1ebd-4318-bc1b-7240aaa49fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>v2.4.2 (build: 44de479_03032023)</value>
      <webElementGuid>5829095b-55c2-489d-8b3a-b9d77d33d6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appVersion&quot;)</value>
      <webElementGuid>eb1c6749-5679-4d12-8d85-15ab952bc9f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='appVersion']</value>
      <webElementGuid>f91bf281-b649-4385-96bb-000daa2f5e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AboutApplication']/div/span</value>
      <webElementGuid>7615a189-25c4-48ea-8f76-c48e865c4779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PowerInsight'])[1]/following::span[1]</value>
      <webElementGuid>d4ba7ebe-0ffc-4c99-8c07-8e83db7042eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number'])[1]/preceding::span[1]</value>
      <webElementGuid>dbdd6d92-08fe-4d48-8907-3e3829db4c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Part Number'])[1]/preceding::span[2]</value>
      <webElementGuid>5f3edd6b-3aa9-4218-9172-766bf6c7d131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='v2.4.2 (build: 44de479_03032023)']/parent::*</value>
      <webElementGuid>1e051c30-8a4b-4bd0-bfd9-d86eeb5ad630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>aff99f84-106c-4cfa-88c8-6478e3a89fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'appVersion' and (text() = 'v2.4.2 (build: 44de479_03032023)' or . = 'v2.4.2 (build: 44de479_03032023)')]</value>
      <webElementGuid>21b83f66-0848-4216-ac81-420497f8d0d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
