<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Time Interval</name>
   <tag></tag>
   <elementGuidId>672c4ab5-8f02-4780-a23e-4065d48ab6b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ascentAP10TimeInterval_a1d86e5d-8c4a-45dc-adf0-c14327d819dc-button > span.ui-selectmenu-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ascentAP10TimeInterval_a1d86e5d-8c4a-45dc-adf0-c14327d819dc-button']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bcc3b051-f9cf-4495-ae39-68884b4fe591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectmenu-text</value>
      <webElementGuid>b6a2e872-4049-45d0-8dbf-4237fe4391a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 hour</value>
      <webElementGuid>867c12f5-e594-47c5-bae6-52827e08818d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ascentAP10TimeInterval_a1d86e5d-8c4a-45dc-adf0-c14327d819dc-button&quot;)/span[@class=&quot;ui-selectmenu-text&quot;]</value>
      <webElementGuid>89b9c088-aed5-41e9-a6c3-91e2728a1d55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ascentAP10TimeInterval_a1d86e5d-8c4a-45dc-adf0-c14327d819dc-button']/span[2]</value>
      <webElementGuid>22822160-6bcc-4636-9f33-7445508b7459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Interval'])[1]/following::span[3]</value>
      <webElementGuid>f2e728e0-ef27-49fd-8de5-814b98806c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trigger Position (%)'])[1]/preceding::span[1]</value>
      <webElementGuid>5c5ce0b0-a510-4600-9fb9-e39363802b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sampling Rate (Hz)'])[1]/preceding::span[3]</value>
      <webElementGuid>aff06732-e3d5-4a80-97a3-f43819283d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div[2]/div/div/span/span[2]</value>
      <webElementGuid>590ad988-3205-4403-b52e-52d3232a6e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1 hour' or . = '1 hour')]</value>
      <webElementGuid>dda3fdd2-8d31-495d-9a3e-fb73d605abfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
