<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TriggerValue</name>
   <tag></tag>
   <elementGuidId>951a8745-e749-4b8b-91ff-1a9fb5a8ced8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@title, 'Trigger position')]//span[@class='val']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ascentAP10TriggerPosition_a1d86e5d-8c4a-45dc-adf0-c14327d819dc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ec40ab8b-5023-474c-9e30-2f06d0567bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ascentAP10TriggerPosition_a1d86e5d-8c4a-45dc-adf0-c14327d819dc</value>
      <webElementGuid>501a8da4-3fc5-469e-aa52-fd9c96351e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>val</value>
      <webElementGuid>442b9a57-3555-41d1-a3f7-b00a36052668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>b5548b94-f8d6-4c21-ac91-84a70d24904b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ascentAP10TriggerPosition_a1d86e5d-8c4a-45dc-adf0-c14327d819dc&quot;)</value>
      <webElementGuid>85116b72-57c0-47ca-9c47-1ec1e7f51491</webElementGuid>
   </webElementProperties>
</WebElementEntity>
