<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hourly Capture Limit</name>
   <tag></tag>
   <elementGuidId>ae46cc8e-e8d3-4702-98f0-62c73ba1dad3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@class, 'hourlyCaptureLimit')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ascentAP10HourlyCaptures_a1d86e5d-8c4a-45dc-adf0-c14327d819dc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>156fef3d-f43f-489f-aa48-765ddb6311e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>176a3347-d772-4897-b8af-481b787ee8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>408698c8-982b-46e6-b5c4-df862fbeccc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>44be4049-44d3-4403-8934-adee51bd71a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control tooltipster hourlyCaptureLimit tooltipstered</value>
      <webElementGuid>0c5e61ab-c688-478f-acf5-25468b6ec78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ascentAP10HourlyCaptures_a1d86e5d-8c4a-45dc-adf0-c14327d819dc</value>
      <webElementGuid>0ec3c4d6-28f7-413c-91e3-8b94df6dc28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ascentAP10HourlyCaptures_a1d86e5d-8c4a-45dc-adf0-c14327d819dc</value>
      <webElementGuid>d8f1f90b-7c1d-4278-b934-6d798c609050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ascentAP10HourlyCaptures_a1d86e5d-8c4a-45dc-adf0-c14327d819dc&quot;)</value>
      <webElementGuid>d12d4c66-44b4-48c1-a9e2-26a93bdb2f49</webElementGuid>
   </webElementProperties>
</WebElementEntity>
