<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Advanced Options</name>
   <tag></tag>
   <elementGuidId>8f9d36d9-df19-4806-a062-6463e375606a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Advanced options&quot;] > span.navText > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='sidebar']/li[3]/a/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0f89aa61-d0d3-4c66-ad7d-e2f720074060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Advanced Options</value>
      <webElementGuid>55327525-3e45-4792-8db0-e7b0170f9608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/li[3]/a[1]/span[@class=&quot;navText&quot;]/span[1]</value>
      <webElementGuid>d54e1445-dcdd-49d7-8cda-bb6f5035ff85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebar']/li[3]/a/span[2]/span</value>
      <webElementGuid>62f79513-3aa6-4bb9-9792-52a16243372b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::span[3]</value>
      <webElementGuid>42291ae9-0bcc-476f-be8f-c8af3b1bbe4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License Options'])[1]/preceding::span[2]</value>
      <webElementGuid>a298c303-4b11-4652-8483-2192c3c83283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::span[5]</value>
      <webElementGuid>da31d351-a3c5-4cae-8fcc-2ce3f7b25d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Advanced Options']/parent::*</value>
      <webElementGuid>9e5becb1-baeb-4064-aac3-640dc954531b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/span[2]/span</value>
      <webElementGuid>e381feb6-756d-4298-9697-4cd5b232b466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Advanced Options' or . = 'Advanced Options')]</value>
      <webElementGuid>4adce10a-3e85-4c81-9abe-ceb42a5e233b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
